This fixes issue #1
twijg/react-safeinnerhtml pull request #2
Opened 2017-04-07 12:14 UTC by hoest

@WiebeCnossen Do you think it is possible to change to this way of parsing the HTML?

2017-04-07 13:12 UTC, WiebeCnossen requested changes

2017-04-07 13:12 UTC, WiebeCnossen commented on dist/utils.js
> +  return new DOMParser().parseFromString(innerHTML, "application/xhtml+xml");
Als dit de oplossing is, dan denk ik dat we een boolean property xhtml (default: false) moeten maken. Want in principe is het idee dat je er gewoon html ingooit en dat het werkt. Het is niet de bedoeling dat hij ervan uitgaat dat het xhtml is.

2017-04-10 07:51 UTC, hoest commented on dist/utils.js
> +  return new DOMParser().parseFromString(innerHTML, "application/xhtml+xml");
Gewenste aanpassing doorgevoerd

2017-04-10 08:27 UTC, WiebeCnossen approved these changes
OK!

2017-04-10 08:27 UTC, merged